# Generated by Django 2.2.16 on 2022-07-14 17:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('content', '0002_auto_20220714_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
