# Generated by Django 3.2.14 on 2022-07-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20220714_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='pub_date',
            new_name='year',
        ),
    ]
