# Generated by Django 2.2.16 on 2022-07-21 22:21

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[api.validators.validate_date], verbose_name='Дата выхода'),
        ),
    ]
